#!/usr/bin/env python3
"""Data-quality checks + concrete data-quirk examples -> analysis/backtests/output/.

Outputs
-------
    data_quality_report.md          narrative report with tables (every number computed here)
    dq_coverage.csv                 missing minutes / extended hours / fractional volume / integrity by ticker-year
    dq_raw_duplicate_sample.csv     raw re-fetch vs cache (duplicates, mismatches)
    dq_outliers.csv, dq_outlier_examples.csv
    dq_splits.csv                   split discontinuities (unadjusted) vs continuity (adjusted)
    dq_soxl_soxs_consistency.csv    SOXL vs SOXS vs SOXX consistency by year
    dq_daily_vs_minute.csv          daily bars vs minute bars reconciliation
    dq_auction_prints.csv           opening / closing cross prints and the bars they land in
    dq_bar_rebuild.csv              one minute bar rebuilt from trades using condition update rules
"""
from __future__ import annotations

import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from soxlab import api, config, pipeline  # noqa: E402
from soxlab import calendar as scal  # noqa: E402
from soxlab import data as sdata  # noqa: E402
from soxlab import quality as q  # noqa: E402

OUT = config.OUTPUT_DIR


def trades_window(T: str, a: str, b: str) -> pd.DataFrame:
    t0 = pd.Timestamp(a, tz=config.TZ).value
    t1 = pd.Timestamp(b, tz=config.TZ).value
    df = pd.DataFrame(api.get_all(f"/v3/trades/{T}", {"timestamp.gte": t0, "timestamp.lt": t1, "limit": 50000,
                                                     "sort": "timestamp", "order": "asc"}))
    if df.empty:
        return df
    df["ts"] = pd.to_datetime(df["sip_timestamp"], unit="ns", utc=True).dt.tz_convert(config.TZ)
    df["conditions"] = df["conditions"].apply(lambda c: tuple(c) if isinstance(c, (list, np.ndarray)) else ())
    df["size_f"] = df["decimal_size"].astype(float) if "decimal_size" in df else df["size"].astype(float)
    return df


def condition_rules() -> pd.DataFrame:
    c = pd.read_parquet(config.REF_DIR / "conditions_stocks.parquet")
    c = c[c["type"] == "sale_condition"]
    return c.rename(columns={"update_rules.consolidated.updates_high_low": "upd_hl",
                             "update_rules.consolidated.updates_open_close": "upd_oc",
                             "update_rules.consolidated.updates_volume": "upd_v"})[["id", "name", "upd_hl", "upd_oc", "upd_v"]]


def rebuild_bar(tr: pd.DataFrame, rules: pd.DataFrame, allow: tuple = ()) -> dict:
    """Rebuild OHLCV from prints using consolidated update rules; condition ids in ``allow`` are treated
    as fully eligible (used to test whether Form T / extended-hours prints enter the aggregates)."""
    r = rules.set_index("id")

    def ok(conds, col):
        return all(True if c in allow else (bool(r.loc[c, col]) if c in r.index and pd.notna(r.loc[c, col]) else True)
                   for c in conds)
    hl = tr[tr["conditions"].apply(lambda c: ok(c, "upd_hl"))]
    oc = tr[tr["conditions"].apply(lambda c: ok(c, "upd_oc"))]
    vv = tr[tr["conditions"].apply(lambda c: ok(c, "upd_v"))]
    nan = float("nan")
    return {"o": oc["price"].iloc[0] if len(oc) else nan, "h": hl["price"].max() if len(hl) else nan,
            "l": hl["price"].min() if len(hl) else nan, "c": oc["price"].iloc[-1] if len(oc) else nan,
            "v": vv["size_f"].sum(), "n_trades_all": len(tr), "v_all_prints": tr["size_f"].sum()}


def minute_bar(T: str, day: str, hhmm: str, adjusted: bool = False) -> dict:
    b = sdata.load_minute_bars(T, adjusted, day, day)
    m = int(hhmm[:2]) * 60 + int(hhmm[3:])
    r = b[b["mod"] == m]
    return r.iloc[0][["o", "h", "l", "c", "v", "n"]].to_dict() if len(r) else {}


def main() -> None:
    t0 = time.time()
    OUT.mkdir(parents=True, exist_ok=True)
    cal = scal.load_calendar()
    rep = ["# Data-quality report (soxlab)", "",
           f"Generated by `scripts/run_quality.py` on {pd.Timestamp.now(tz=config.TZ):%Y-%m-%d %H:%M} ET from the "
           f"Massive cache in `data/soxlab/` ({config.HISTORY_START} -> {config.HISTORY_END}, {len(cal)} trading days, "
           f"{int(cal['is_half_day'].sum())} early-close days). Every number below is computed from downloaded data.", ""]

    # 1. coverage / integrity
    cov = q.coverage(config.TICKERS, cal)
    cov.to_csv(OUT / "dq_coverage.csv", index=False)
    piv = cov.pivot_table(index="ticker", columns="year", values="rth_missing_pct").round(3)
    rep += ["## 1. Missing (zero-trade) minutes in the regular session", "",
            "Massive emits a minute bar only when at least one eligible trade prints, so zero-trade minutes are "
            "absent (not zero-volume rows). Percent of expected 09:30-15:59 minutes (12:59 on half-days) with no bar:", "",
            q.md_table(piv.reset_index(), "{:.3f}"), "",
            "Extended hours (04:00-09:29 and 16:00-19:59): mean bars per day and share of total volume:", "",
            q.md_table(cov[cov["ticker"].isin(["SOXL", "SOXS", "SOXX"])][["ticker", "year", "pre_bars_per_day",
                       "post_bars_per_day", "ext_volume_share_pct", "fractional_volume_bars_pct"]], "{:.1f}"), "",
            "Integrity counters over all cached bars (duplicate timestamps, bars not aligned to the minute, "
            "high/low inconsistent with open/close, bar VWAP outside [low, high], non-positive volume):", "",
            q.md_table(cov.groupby("ticker")[["dup_timestamps_in_cache", "bars_not_on_minute", "ohlc_inconsistent",
                                              "vw_outside_hl", "nonpositive_volume"]].sum().reset_index(), "{:.0f}"), "",
            "Bar VWAP (`vw`) outside [low, high] is a data property, not an error: `vw` includes volume-only prints "
            "(odd lots, Form T, average-price trades) whose prices do not update high/low. Share of bars affected (2025):", "",
            q.md_table(cov[cov["year"] == 2025][["ticker", "vw_outside_hl_rth_pct", "vw_outside_hl_ext_pct"]], "{:.3f}"), "",
            "Fractional-share volume (unadjusted bars): first bar with non-integer volume per ticker (none before 2026):", "",
            q.md_table(cov[cov["first_fractional_volume_bar"] != ""].groupby("ticker")["first_fractional_volume_bar"].min().reset_index(), "{}"), ""]

    # 2. raw duplicates / cache reproducibility
    dup = q.raw_duplicate_sample(["SOXL", "SOXS", "SOXX"])
    dup.to_csv(OUT / "dq_raw_duplicate_sample.csv", index=False)
    rep += ["## 2. Duplicates and reproducibility (raw re-fetch of sample months vs cache, unadjusted)", "",
            q.md_table(dup, "{:.0f}"), ""]

    # 3. outliers
    osum, oex = q.outliers(config.TICKERS)
    osum.to_csv(OUT / "dq_outliers.csv", index=False)
    oex.to_csv(OUT / "dq_outlier_examples.csv", index=False)
    rep += ["## 3. Outliers (isolated spikes: |1-min log return| > 5% followed by an opposite move > 5%)", "",
            q.md_table(osum, "{:.0f}"), "", "First examples per ticker:", "", q.md_table(oex, "{:.4g}"), ""]

    # 4. splits
    spl = q.split_checks(config.TICKERS)
    spl.to_csv(OUT / "dq_splits.csv", index=False)
    s_ev = spl[spl["execution_date"] != "ALL"]
    rep += ["## 4. Split discontinuities (unadjusted) vs adjusted continuity", "",
            "`/v3/reference/splits` history inside the cache window; the unadjusted open on the execution date divided "
            "by the prior unadjusted close should be ~ split_from/split_to; the adjusted ratio should look like a normal gap.", "",
            q.md_table(s_ev[["ticker", "execution_date", "split_from", "split_to", "expected_unadj_open_over_prev_close",
                             "unadj_open_over_prev_close", "adj_open_over_prev_close", "unadj_prev_close", "unadj_open"]], "{:.4g}"), "",
            "Unadjusted/adjusted factor changes on non-split dates (should be 0):", "",
            q.md_table(spl[spl["execution_date"] == "ALL"][["ticker", "factor_changes_off_split_dates", "examples"]], "{:.0f}"), ""]

    # 5. SOXL vs SOXS consistency
    ctx = pipeline.load_context(verbose=False)
    cons = q.soxl_soxs_consistency(ctx)
    cons.to_csv(OUT / "dq_soxl_soxs_consistency.csv", index=False)
    rep += ["## 5. SOXL vs SOXS (and 3x SOXX) consistency", "",
            "Daily returns from official closes; minute returns from regular-session bars present in both tickers; "
            "`div_since_close` = SOXL + SOXS return since the prior official close (0 under perfect -/+3x tracking).", "",
            q.md_table(cons, "{:.3f}"), ""]

    # 6. daily vs minute
    dvm = q.daily_vs_minute(config.TICKERS, cal)
    dvm.to_csv(OUT / "dq_daily_vs_minute.csv", index=False)
    rep += ["## 6. Daily bars vs minute bars (unadjusted)", "",
            "The daily bar close is the official (closing-auction) price; the last regular-session minute bar close "
            "is the last eligible continuous trade before 16:00:00. Volume ratios show what the daily bar counts.", "",
            q.md_table(dvm, "{:.3f}"), ""]

    # 7. quirks with concrete examples from trades
    rules = condition_rules()
    excl = rules[(rules["upd_hl"] == False) | (rules["upd_oc"] == False) | (rules["upd_v"] == False)]  # noqa: E712
    rep += ["## 7. Trade conditions that bar construction excludes (from /v3/reference/conditions, consolidated rules)", "",
            q.md_table(excl, "{}"), ""]
    day = "2026-09-25"
    auc = []
    for T in config.TRADED:
        for (a, b, lab) in ((f"{day} 09:30:00", f"{day} 09:30:05", "open"), (f"{day} 16:00:00", f"{day} 16:00:05", "close")):
            tr = trades_window(T, a, b)
            top = tr.sort_values("size_f", ascending=False).head(2)
            for _, r in top.iterrows():
                auc.append({"ticker": T, "cross": lab, "ts_et": r["ts"].strftime("%H:%M:%S.%f"), "price": r["price"],
                            "size": r["size_f"], "exchange": r["exchange"], "conditions": ",".join(map(str, r["conditions"])),
                            "lands_in_bar": r["ts"].strftime("%H:%M")})
    auc = pd.DataFrame(auc)
    auc.to_csv(OUT / "dq_auction_prints.csv", index=False)
    # does the closing cross appear in minute bars? daily volume - sum(all minute volume) vs cross size
    xc = []
    for T in config.TRADED:
        for dd in ("2024-03-13", "2025-03-12", "2025-09-10", "2026-03-11", "2026-09-16", "2026-09-25"):
            tr = trades_window(T, f"{dd} 16:00:00", f"{dd} 16:00:05")
            cross = tr[tr["conditions"].apply(lambda c: 8 in c)]["size_f"].sum() if len(tr) else np.nan
            op = trades_window(T, f"{dd} 09:30:00", f"{dd} 09:30:05")
            ocross = op[op["conditions"].apply(lambda c: 17 in c)]["size_f"].sum() if len(op) else np.nan
            bm = sdata.load_minute_bars(T, False, dd, dd)
            dv = sdata.load_daily(T, False).loc[dd, "v"]
            xc.append({"ticker": T, "date": dd, "daily_volume": dv, "sum_minute_volume_all_sessions": bm["v"].sum(),
                       "difference": dv - bm["v"].sum(), "closing_cross_size(cond 8)": cross,
                       "opening_cross_size(cond 17)": ocross})
    xc = pd.DataFrame(xc)
    xc.to_csv(OUT / "dq_closing_cross_vs_bars.csv", index=False)
    bars = []
    for T in config.TRADED:
        dly = sdata.load_daily(T, False).loc[day]
        for hh in ("09:30", "15:59", "16:00"):
            bars.append({"ticker": T, "bar": hh, **minute_bar(T, day, hh)})
        bars.append({"ticker": T, "bar": "daily", "o": dly["o"], "h": dly["h"], "l": dly["l"], "c": dly["c"], "v": dly["v"],
                     "n": dly["n"]})
    bars = pd.DataFrame(bars)
    rep += [f"### Opening / closing cross prints ({day}, largest prints in the first 5 s after 09:30:00 and 16:00:00)", "",
            q.md_table(auc, "{:.6g}"), "", "Bars around them (unadjusted) and the daily bar:", "", q.md_table(bars, "{:.6g}"), "",
            "Daily volume minus the sum of ALL minute-bar volume (04:00-20:00) vs the closing-cross print size "
            "(condition 8 print in the first 5 s after 16:00):", "", q.md_table(xc, "{:.0f}"), ""]
    # rebuild one bar
    rb_rows = []
    for T, hh in (("SOXL", "10:15"), ("SOXS", "10:15"), ("SOXL", "04:30")):
        tr = trades_window(T, f"{day} {hh}:00", (pd.Timestamp(f"{day} {hh}") + pd.Timedelta(minutes=1)).strftime("%Y-%m-%d %H:%M:%S"))
        if tr.empty:
            continue
        rb = rebuild_bar(tr, rules)
        rb2 = rebuild_bar(tr, rules, allow=(12,))
        rb3 = rebuild_bar(tr, rules, allow=(12, 37))
        agg = minute_bar(T, day, hh)
        frac = tr[(tr["size_f"] % 1) != 0]
        rb_rows.append({"ticker": T, "minute": f"{day} {hh}", **{f"rebuilt_{k}": v for k, v in rb.items()},
                        **{f"rebuilt_formT_ok_{k}": v for k, v in rb2.items() if k in "ohlcv"},
                        **{f"rebuilt_formT_and_oddlots_ok_{k}": v for k, v in rb3.items() if k in "ohlc"},
                        **{f"agg_{k}": v for k, v in agg.items()},
                        "fractional_prints": len(frac), "fractional_volume": float(frac["size_f"].sum()),
                        "odd_lot_prints(cond 37)": int(tr["conditions"].apply(lambda c: 37 in c).sum())})
    rbd = pd.DataFrame(rb_rows)
    rbd.to_csv(OUT / "dq_bar_rebuild.csv", index=False)
    rep += ["### A minute bar rebuilt from /v3/trades with the consolidated update rules vs the /v2/aggs bar", "",
            q.md_table(rbd.T.reset_index().rename(columns={"index": "field"}), "{:.6g}"), ""]
    # DST, half-day, split examples
    ex = []
    for dday in ("2026-03-06", "2026-03-09", "2025-10-31", "2025-11-03"):
        b = sdata.load_minute_bars("SOXL", True, dday, dday)
        r = b[b["mod"] == config.RTH_START_MIN].iloc[0]
        ex.append({"date": dday, "t_ms_utc": int(r["t"]),
                   "utc": pd.Timestamp(int(r["t"]), unit="ms", tz="UTC").strftime("%H:%M"),
                   "et": r["ts"].strftime("%H:%M %Z")})
    rep += ["### Timestamp convention and DST", "",
            "`t` is the bar START in UTC epoch milliseconds; the first regular-session bar (09:30 ET) is 14:30 UTC "
            "under EST and 13:30 UTC under EDT:", "", q.md_table(pd.DataFrame(ex), "{}"), ""]
    hd = "2025-11-28"
    b = sdata.load_minute_bars("SOXL", False, hd, hd)
    win = pd.cut(b["mod"], [240, 570, 780, 960, 1020, 1200], right=False,
                 labels=["04:00-09:29", "09:30-12:59", "13:00-15:59", "16:00-16:59", "17:00-19:59"])
    hdv = b.groupby(win, observed=False).agg(bars=("v", "size"), volume=("v", "sum")).reset_index()
    rep += [f"### Early-close (half-day) example: SOXL {hd}", "", q.md_table(hdv, "{:.0f}"), ""]
    rep += ["Detected early-close days: " + ", ".join(cal.index[cal["is_half_day"]].strftime("%Y-%m-%d")), ""]
    rep += [f"Build time {time.time() - t0:.0f}s."]
    (OUT / "data_quality_report.md").write_text("\n".join(rep))
    print(f"wrote {OUT / 'data_quality_report.md'} in {time.time() - t0:.0f}s")


if __name__ == "__main__":
    main()
